name: Check 32-bit installation without orjson

on:
  push:

jobs:
  check_32bit:
    runs-on: raspberry pi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Python version and architecture
        run: |
          python --version
          python -c "import platform; print(platform.architecture())"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Run
        run: main.py
